from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Sequence

import numpy as np
import torch
import torch.nn as nn

from ..data import get_loaders
from ..layerwrapper import WrappedGPT
from .wanda_weight import (
    ATTENTION_MODULES,
    MLP_MODULES,
    apply_guided_wanda_module_,
    get_submodule,
    transformer_layers,
)


class _StopCapture(RuntimeError):
    pass


@dataclass
class CalibrationState:
    inps: torch.Tensor
    outs: torch.Tensor
    attention_mask: torch.Tensor | None
    position_ids: torch.Tensor | None
    position_embeddings: tuple[torch.Tensor, torch.Tensor] | None


def _as_device(value) -> torch.device:
    """Normalize Accelerate device-map entries (int, str, or torch.device)."""
    if isinstance(value, torch.device):
        return value
    if isinstance(value, int):
        return torch.device(f"cuda:{value}")
    if value in {"disk", "cpu"}:
        return torch.device("cpu")
    return torch.device(value)


def _embedding_device(model: torch.nn.Module) -> torch.device:
    if hasattr(model, "hf_device_map") and "model.embed_tokens" in model.hf_device_map:
        return _as_device(model.hf_device_map["model.embed_tokens"])
    return model.get_input_embeddings().weight.device


def capture_first_layer_inputs(
    model: torch.nn.Module,
    dataloader: Sequence,
    nsamples: int,
    seqlen: int,
) -> CalibrationState:
    """Dynamic-size counterpart of Wanda's calibration-input catcher."""
    layers = transformer_layers(model)
    device = _embedding_device(model)
    dtype = next(iter(model.parameters())).dtype
    hidden_size = int(model.config.hidden_size)
    inps = torch.zeros(
        (nsamples, seqlen, hidden_size), dtype=dtype, device=device
    )
    cache = {
        "i": 0,
        "attention_mask": None,
        "position_ids": None,
        "position_embeddings": None,
    }

    original = layers[0]

    class Catcher(nn.Module):
        def __init__(self, module):
            super().__init__()
            self.module = module

        def forward(self, inp, **kwargs):
            i = int(cache["i"])
            if i >= nsamples:
                raise _StopCapture
            if inp.shape[1] != seqlen:
                raise ValueError(
                    f"calibration input length {inp.shape[1]} != requested {seqlen}"
                )
            inps[i].copy_(inp[0])
            cache["i"] = i + 1
            cache["attention_mask"] = kwargs.get("attention_mask")
            cache["position_ids"] = kwargs.get("position_ids")
            cache["position_embeddings"] = kwargs.get("position_embeddings")
            raise _StopCapture

    layers[0] = Catcher(original)
    try:
        for batch in dataloader:
            if cache["i"] >= nsamples:
                break
            try:
                model(batch[0].to(device), use_cache=False)
            except _StopCapture:
                pass
    finally:
        layers[0] = original

    captured = int(cache["i"])
    if captured != nsamples:
        raise RuntimeError(f"captured {captured}/{nsamples} calibration samples")
    return CalibrationState(
        inps=inps,
        outs=torch.zeros_like(inps),
        attention_mask=cache["attention_mask"],
        position_ids=cache["position_ids"],
        position_embeddings=cache["position_embeddings"],
    )


def _move_optional(value, device):
    return None if value is None else value.to(device)


def _layer_kwargs(state: CalibrationState, device: torch.device) -> dict:
    kwargs = {}
    if state.attention_mask is not None:
        kwargs["attention_mask"] = state.attention_mask.to(device)
    if state.position_ids is not None:
        kwargs["position_ids"] = state.position_ids.to(device)
    if state.position_embeddings is not None:
        kwargs["position_embeddings"] = tuple(
            item.to(device) for item in state.position_embeddings
        )
    return kwargs


def apply_sequential_paper_wanda_masks_(
    model: torch.nn.Module,
    tokenizer,
    scores_by_type: Mapping[str, Mapping[int, np.ndarray]],
    targets: tuple[str, ...],
    mlp_ratio: float,
    attention_ratio: float,
    calib_dataset: str,
    nsamples: int,
    seqlen: int,
    seed: int,
    row_spread: float = 0.01,
    row_temperature: float = 1.0,
    guidance_strength: float = 0.01,
    chunk_rows: int = 256,
) -> list[dict]:
    """Official-Wanda-style sequential calibration and layerwise pruning.

    The model input to layer l is generated by already-pruned layers 0..l-1.
    This is the crucial behavior missing from v4 and is the main reason this
    implementation remains close to Wanda's low-PPL 50% operating point.
    """
    if nsamples < 4:
        raise ValueError("sequential Wanda calibration needs at least four samples")
    if seqlen < 8:
        raise ValueError("seqlen must be >= 8")
    dataloader, _ = get_loaders(
        calib_dataset,
        nsamples=nsamples,
        seed=seed,
        seqlen=seqlen,
        tokenizer=tokenizer,
    )
    original_use_cache = getattr(model.config, "use_cache", None)
    if original_use_cache is not None:
        model.config.use_cache = False
    state = capture_first_layer_inputs(model, dataloader, nsamples, seqlen)
    layers = transformer_layers(model)
    summaries: list[dict] = []

    try:
        for layer_id, layer in enumerate(layers):
            dev = layer.self_attn.q_proj.weight.device
            state.inps = state.inps.to(dev)
            state.outs = state.outs.to(dev)
            kwargs = _layer_kwargs(state, dev)
            module_names = []
            if "attention" in targets:
                module_names.extend(ATTENTION_MODULES)
            if "mlp" in targets:
                module_names.extend(MLP_MODULES)
            wrappers = {
                name: WrappedGPT(get_submodule(layer, name), layer_id, name)
                for name in module_names
            }

            handles = []
            for name, wrapper in wrappers.items():
                def make_hook(w):
                    def hook(_module, inputs, output):
                        w.add_batch(inputs[0].detach(), output.detach())
                    return hook
                handles.append(get_submodule(layer, name).register_forward_hook(make_hook(wrapper)))

            with torch.no_grad():
                for sample in range(nsamples):
                    state.outs[sample] = layer(
                        state.inps[sample].unsqueeze(0), **kwargs
                    )[0]
            for handle in handles:
                handle.remove()

            layout_num_heads = int(
                getattr(layer.self_attn, "num_heads", 0)
                or model.config.num_attention_heads
            )
            layout_num_kv = int(
                getattr(layer.self_attn, "num_key_value_heads", 0)
                or getattr(model.config, "num_key_value_heads", layout_num_heads)
            )
            head_dim = int(
                getattr(layer.self_attn, "head_dim", 0)
                or layer.self_attn.q_proj.out_features // layout_num_heads
            )
            if "attention" in targets and layout_num_heads != layout_num_kv:
                raise ValueError(
                    "Llama-2 MHA is supported; GQA requires a separate q-to-kv mapping"
                )

            with torch.no_grad():
                for module_name in module_names:
                    unit_type = (
                        "attention" if module_name.startswith("self_attn.") else "mlp"
                    )
                    ratio = attention_ratio if unit_type == "attention" else mlp_ratio
                    module = get_submodule(layer, module_name)
                    summary = apply_guided_wanda_module_(
                        module_name,
                        module,
                        wrappers[module_name].scaler_row,
                        np.asarray(scores_by_type[unit_type][layer_id]),
                        ratio,
                        head_dim,
                        row_spread=row_spread,
                        row_temperature=row_temperature,
                        guidance_strength=guidance_strength,
                        chunk_rows=chunk_rows,
                    )
                    summary["layer"] = layer_id
                    summaries.append(summary)
                    print(
                        f"  [sequential-wanda] layer={layer_id:02d} "
                        f"module={module_name:<20} target={ratio:.4f} "
                        f"actual={summary['actual_ratio']:.6f}",
                        flush=True,
                    )

                # Propagate the pruned layer output to the next layer, exactly
                # as in Wanda's sequential implementation.
                for sample in range(nsamples):
                    state.outs[sample] = layer(
                        state.inps[sample].unsqueeze(0), **kwargs
                    )[0]
            state.inps, state.outs = state.outs, state.inps
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
    finally:
        if original_use_cache is not None:
            model.config.use_cache = original_use_cache
    return summaries
